#!/bin/sh

# Basics like verbosity and settings
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -Iv" \
	mkd="mkdir -pv" \
	yt="yt-dlp --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	tmux="tmux -f ~/.config/tmux/tmux.conf" \
	nnn="nnn -a" \
	lsblk='lsblk -o name,size,type,mountpoint,label' \
	lsblkv='lsblk -o name,size,type,fstype,mountpoint,label,uuid' \
	df='df --total -h' \
	bat='PAGER="less -R" bat' \
	rmg='MESA_GL_VERSION_OVERRIDE=3.3 RMG' \
	stig='stig -c ~/.config/pipx/rc'

# Colorize commands when possible
alias \
	ls="ls -hN --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi --force" \
	less="less -r"

# Others
alias \
	la="lsd -la" \
	ll="lsd -l" \
	lsa="lsd -a" \
	vim="nvim -u ~/.config/nvim/minimal.vim" \
	scim="sc-im" \
	wm-name="xprop | grep 'WM_NAME'" \
	film="mpv --sub-auto=all --sub-file-paths=Subs" \

fr() { # FZF Repos
	choices=$(find "$HOME"/repos/ -maxdepth 2 -type d)
	cd "$(echo "$choices" | fzf --layout=reverse --height 40%)" || exit 1
}

allatexcomp() { # Compile all latex documents in a directory
	for file in $(ls | grep ".tex")
	do
		xelatex "$file"
		xelatex "$file"
		texclear "$file"
	done
}

# vim: filetype=sh
