require('plug-config.cmp')
require('plug-config.navigator')
require('plug-config.neorg')
require('plug-config.lsp')
require('plug-config.lualine')
require('plug-config.nvim-colorizer')
require('plug-config.nvim-tree')
require('plug-config.treesitter')
