#!/bin/sh

# Basics like verbosity and settings
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -Iv" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	tmux="tmux -f ~/.config/tmux/tmux.conf" \
	nnn="nnn -a" \
	lsblk='lsblk -o name,size,type,mountpoint,label' \
	lsblkv='lsblk -o name,size,type,fstype,mountpoint,label,uuid' \
	df='df --total -h' \
	bat='PAGER="less -R" bat' \
	stig='stig -c ~/.config/pipx/rc'

# Colorize commands when possible
alias \
	ls="ls -hN --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi --force" \
	less="less -r"

# Others
alias \
	la="lsd -la" \
	ll="lsd -l" \
	lsa="lsd -a" \
	lexa="exa -Tla" \
	lext="exa -Tl" \
	vim="nvim" \
	open="xdg-open" \
	scim="sc-im" \
	wm-name="xprop | grep 'WM_NAME'" \
	film="mpv --sub-auto=all --sub-file-paths=Subs"

fr() { # FZF Repos
	choices=$(find "$HOME"/repos/ -maxdepth 2 -type d && find /home/luc/work/ -maxdepth 5 -type d)
	cd "$(echo "$choices" | fzf --layout=reverse --height 40%)" || exit 1
}

ft() { # FZF Tmux
	config=$(find "$HOME"/.config/tmux/configs/ -maxdepth 1 | sed '1d' | fzf --layout=reverse --height 40%) 
	sh "$config" 2>/dev/null || :
}

ce() { # Edit Config
	choices="$(find "$HOME"/.dotfiles/ -maxdepth 4 -path /home/luc/.dotfiles/.git -prune -o -name "*")"
	nvim "$(echo "$choices" | fzf --layout=reverse --height 40%)" || exit 1
}

haste() { # Hase pastebin
	a=$(cat)
	curl -X POST -s -d "$a" https://hastebin.com/documents | awk -F '"' '{print "https://hastebin.com/"$4}'
}

allatexcomp() { # Compile all latex documents in a directory
	for file in $(ls | grep ".tex")
	do
		xelatex "$file"
	done
	ls | grep ".aux" >/dev/null && command rm ./*.aux
	ls | grep ".log" >/dev/null && command rm ./*.log
}
# vim: filetype=sh
